# config.yaml

path: C:\Users\user\Downloads\project-4-at-2024-10-30-12-26-ba65eade  # Путь к папке с вашим датасетом
train: images/   # Путь к папке с тренировочными изображениями
val: images/                # Путь к папке с валидационными изображениями

nc: 1       # Укажите количество классов в вашем датасете
names: ['rokki']  # Список с названиями классов
